dirs:
  - .

excludedDirs:
  - AFLplusplus

useGitIgnore: true

ignorePatterns:
  - pattern: "https://www.romu-random.org/"
  - pattern: "https://github.com/LibAFLminusminus/LibAFLminusminus"

aliveStatusCodes:
  - 0
  - 200
  - 403
