version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directories:
      - "/fuzzers/**"
    schedule:
      interval: "weekly"
    groups:
      fuzzers:
        patterns:
          - "*"
