# tested fuzzers are now stored here
# mostly because there is no other way to provide this list to dependabot
# but we can use it to infer the fuzzer list for the other parts of the CI

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directories:
      # normal fuzzers
      - "/fuzzers/baby/baby_cmplog"
      - "/fuzzers/baby/baby_corpus_sharing"
      - "/fuzzers/baby/baby_forkserver"
      - "/fuzzers/baby/baby_inprocess"

      - "/fuzzers/inprocess/sqlite"

      - "/fuzzers/binary_only/frida_libpng"
      - "/fuzzers/binary_only/intel_pt_baby_fuzzer"

      - "/fuzzers/structure_aware/baby_fuzzer_nautilus"
    schedule:
      interval: "weekly"
    groups:
      standard-fuzzers:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directories:
      # qemu fuzzers
      - "/fuzzers/baby/baby_nyx"

      - "/fuzzers/binary_only/qemu_launcher"

      - "/fuzzers/full_system/qemu_baremetal"
    schedule:
      interval: "weekly"
    groups:
      qemu-fuzzers:
        patterns:
          - "*"
