name: apt
description: Base packages for Linux jobs

inputs:
  qemu:
    description: Install QEMU dependencies
    required: false
    default: false
  aflplusplus:
    description: Build and install AFLplusplus from the submodule
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Update apt
      shell: bash
      run: sudo apt-get update

    - name: Install base packages
      shell: bash
      run: |
        packages=(
          curl lsb-release wget software-properties-common gnupg unzip
          shellcheck libc6-dev gcc g++ build-essential libfile-mimeinfo-perl
          python3-pip cmake python3 libpython3-dev mold yq libasan8
          python3-dev automake flex bison
          clang llvm llvm-dev lld
        )

        sudo apt-get install -y --no-install-recommends "${packages[@]}"

    - name: Install QEMU packages
      if: ${{ inputs.qemu == 'true' }}
      shell: bash
      run: |
        packages=(
          ninja-build pkg-config libglib2.0-dev libpixman-1-dev python3-venv
          qemu-utils
          gcc-arm-none-eabi
          libnewlib-arm-none-eabi
        )

        sudo apt-get install -y --no-install-recommends "${packages[@]}"

    - name: Build and install AFLplusplus
      if: ${{ inputs.aflplusplus == 'true' }}
      shell: bash
      run: |
        git -C "$GITHUB_WORKSPACE" submodule update --init --checkout --force AFLplusplus
        make -C "$GITHUB_WORKSPACE/AFLplusplus"
        sudo make -C "$GITHUB_WORKSPACE/AFLplusplus" install
