[package]
name = "baby_corpus_sharing"
version = "0.16.0"
authors = ["Romain Malmain <rmalmain@pm.me>"]
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
libaflmm = { path = "../../../crates/libaflmm" }
libaflmm_bolts = { path = "../../../crates/libaflmm_bolts" }

env_logger = "0.11.7"
