import "../../../just/libafl.just"
FUZZER_NAME := "baby_corpus_sharing"

build:
    cargo build --locked --profile {{ PROFILE }}

run: build
    {{ FUZZER }}

test: build
    #!/bin/bash
    set -eu

    timeout 20s {{ FUZZER }} || true

    STATS_FILE="./workdir/worker_receiving/fuzzer_stats"
    if [ ! -f "$STATS_FILE" ]; then
        echo "{{ FUZZER_NAME }}: Stats file not found at $STATS_FILE"
        exit 1
    fi

    CORPUS=$(jq '.corpus' "$STATS_FILE")
    if [ "$CORPUS" -eq 4 ]; then
        echo "{{ FUZZER_NAME }}: Receiving worker has found $CORPUS corpus(es) entries."
    else
        echo "{{ FUZZER_NAME }}: Receiving worker did not receive all corpuses entries (found $CORPUS entries in $STATS_FILE)"
        exit 1
    fi

    EXECS=$(jq '.executions' "$STATS_FILE")
    if [ "$EXECS" -eq 4 ]; then
        echo "{{ FUZZER_NAME }}: Receiving worker has executed $EXECS input(s)."
    else
        echo "{{ FUZZER_NAME }}: Receiving worker did not execute exactly $EXECS inputs (executed $EXECS inputs in $STATS_FILE)"
        exit 1
    fi
