[package]
name = "deexit"
authors = [
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
description = "DeExit: Replace exits with aborts to catch them during in-process fuzzing"
keywords = ["fuzzing", "libafl", "ldpreload"]
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
log = { workspace = true }

[lib]
name = "deexit"
crate-type = ["cdylib"]

[lints]
workspace = true
