[package]
name = "libaflmm_nyx"
authors = ["syheliel <syheliel@gmail.com>"]
description = "libafl using nyx, only avaliable on linux"
keywords = ["fuzzing", "testing", "security"]
categories = ["development-tools::testing", "emulators", "embedded", "os"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libnyx = "0.1.3"
libaflmm = { workspace = true, default-features = true, features = [
  "libaflmm_derive",
  "frida_cli",
] }
libaflmm_bolts = { workspace = true, default-features = true, features = [
  "libaflmm_derive",
  "frida_cli",
] }
libaflmm_targets = { workspace = true, default-features = true, features = [
  "sancov_cmplog",
] }

nix = { workspace = true, default-features = true, features = ["fs"] }
typed-builder = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }                                           # serialization lib

[lints]
workspace = true
