name: apt-base
description: Base packages for Linux jobs

runs:
  using: composite
  steps:
    - name: Install base packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          curl \
          lsb-release \
          wget \
          software-properties-common \
          gnupg \
          shellcheck \
          libc6-dev \
          gcc \
          g++ \
          build-essential \
          libfile-mimeinfo-perl
