[package]
name = "baby_fuzzer_forkserver"
version = "0.14.1"
authors = ["Dongjia Zhang <tokazerkje@outlook.jp>"]
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[dependencies]
env_logger = "0.11.7"
libafl = { path = "../../../crates/libafl" }
libafl_bolts = { path = "../../../crates/libafl_bolts" }
clap = { version = "4.5.18", features = ["derive"] }
