name: setup-llvm
description: Setup LLVM

inputs:
  version:
    description: LLVM version to install
    required: false
    default: "22"

runs:
  using: composite
  steps:
    - name: Cache LLVM ${{ inputs.version }}
      id: cache-llvm
      uses: actions/cache@v5
      with:
        path: |
          /usr/lib/llvm-${{ inputs.version }}
          /usr/bin/clang-${{ inputs.version }}
          /usr/bin/clang++-${{ inputs.version }}
          /usr/bin/llvm-config-${{ inputs.version }}
          /usr/bin/lld-${{ inputs.version }}
          /usr/bin/lldb-${{ inputs.version }}
        key: llvm-${{ inputs.version }}-ubuntu-24.04-v1

    - name: Install LLVM ${{ inputs.version }}
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo flock --timeout 300 /var/lock/github-apt.lock ./llvm.sh "${{ inputs.version }}" all

    - name: Set up LLVM ${{ inputs.version }} alternatives
      shell: bash
      run: |
        sudo update-alternatives --install \
            /usr/bin/clang clang \
            /usr/bin/clang-${{ inputs.version }} 200

    - name: Export LLVM env
      shell: bash
      run: |
        {
          echo "LLVM_CONFIG_PATH=$(which llvm-config-${{ inputs.version }})"
          echo "LIBCLANG_PATH=/usr/lib/llvm-${{ inputs.version }}/lib"
          echo "LLVM_CONFIG=llvm-config-${{ inputs.version }}"
        } >> "$GITHUB_ENV"

    - name: Symlink ASM headers
      shell: bash
      run: |
        if [ ! -e /usr/include/asm ]; then
          sudo ln -s /usr/include/asm-generic /usr/include/asm
        fi
