[package]
name = "qemu_launcher"
version = "0.16.0"
authors = [
  "Romain Malmain <rmalmain@pm.me>",
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
edition = "2024"

[features]
default = ["injections"]
clippy = ["libaflmm_qemu/clippy"] # Only for clippy, don't use.

## Enable fuzzing for injections (where supported)
injections = ["libaflmm_qemu/injections"]

## Set emulator to big endian
be = ["libaflmm_qemu/be"]

#! ## Mutually exclusive architectures
arm = ["libaflmm_qemu/arm"]
x86_64 = ["libaflmm_qemu/x86_64"]
i386 = ["libaflmm_qemu/i386"]
aarch64 = ["libaflmm_qemu/aarch64"]
mips = ["libaflmm_qemu/mips"]
ppc = ["libaflmm_qemu/ppc", "be"]
hexagon = ["libaflmm_qemu/hexagon"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
vergen = { version = "9.1.0", features = ["build", "cargo", "rustc", "si"] }
vergen-git2 = "9.1.0"

[dependencies]
libaflmm = { path = "../../../crates/libaflmm" }
libaflmm_qemu = { path = "../../../crates/libaflmm_qemu", features = [
  "usermode",
  "asan_rust",
  "errors_backtrace",
] }

clap = { version = "4.6.1", features = ["derive", "string"] }
env_logger = { version = "0.11.10" }
log = { version = "0.4.29", features = ["release_max_level_info"] }
mimalloc = "0.1.50"
rangemap = { version = "1.7.1" }
readonly = { version = "0.2.13" }
scudo = "0.1.3"
typed-builder = { version = "0.20.1" }
