[package]
name = "ci_runner"
authors = ["Dongjia Zhang <tokazerkje@outlook.com>"]
description = "libafl CI tools for testing fuzzers"
keywords = ["fuzzing", "testing", "security"]
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]
readme = "../README.md"

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
