//! Custom source-level lints for the `LibAFL` repository.
//!
//! Each lint produces a rustc-style diagnostic on violation.

/// make sure generics are ordered correctly
pub mod generics_order;
/// enforce statement correct ordering
pub mod statement_order;

use std::{io, io::Read, path::PathBuf};

use colored::Colorize;

pub struct Label<'a> {
    pub line: usize,
    pub col: usize,
    pub span_len: usize,
    pub text: &'a str,
    pub primary: bool,
}

pub fn render_diagnostic(
    code: &str,
    message: &str,
    path: &str,
    src: &str,
    primary: Label<'_>,
    secondary: Option<Label<'_>>,
    help: &str,
) -> String {
    let src_lines: Vec<&str> = src.lines().collect();
    let all_labels: Vec<&Label> = secondary.iter().chain(std::iter::once(&primary)).collect();
    let gutter_w = all_labels
        .iter()
        .map(|l| l.line.to_string().len())
        .max()
        .unwrap_or(1);
    let gutter_pad = " ".repeat(gutter_w);
    let sep = "|".blue().bold();

    let mut out = String::new();

    out += &format!(
        "{}{} {}\n",
        format!("error[{code}]").red().bold(),
        ":".bold(),
        message.bold(),
    );

    out += &format!(
        "{gutter_pad}{arrow} {path}:{line}:{col}\n",
        arrow = "-->".blue().bold(),
        line = primary.line,
        col = primary.col,
    );

    out += &format!("{gutter_pad} {sep}\n");

    let mut labels_sorted: Vec<&Label> = all_labels.clone();
    labels_sorted.sort_by_key(|l| l.line);

    let mut prev_line: Option<usize> = None;
    for label in &labels_sorted {
        if let Some(prev) = prev_line
            && label.line > prev + 1
        {
            out += &format!("{}\n", "...".blue().bold());
        }

        let source_line = src_lines.get(label.line - 1).copied().unwrap_or("");
        let ln = format!("{:>w$}", label.line, w = gutter_w).blue().bold();
        out += &format!("{ln} {sep} {source_line}\n");

        let marker = if label.primary { "^" } else { "-" };
        let marker_line = marker.repeat(label.span_len.max(1));
        let (marker_colored, text_colored) = if label.primary {
            (marker_line.red().bold(), label.text.red().bold())
        } else {
            (marker_line.blue().bold(), label.text.blue().bold())
        };
        out += &format!(
            "{gutter_pad} {sep} {offset}{marker_colored} {text_colored}\n",
            offset = " ".repeat(label.col.saturating_sub(1)),
        );

        prev_line = Some(label.line);
    }

    out += &format!("{gutter_pad} {sep}\n");
    out += &format!(
        "{gutter_pad} {eq} {help_label}: {help}",
        eq = "=".blue().bold(),
        help_label = "help".bold(),
    );

    out
}

pub fn underline_len(src_line: &str, col: usize) -> usize {
    let remaining = src_line.get(col.saturating_sub(1)..).unwrap_or("");
    let stop = remaining.find(['{', ';']).unwrap_or(remaining.len());
    remaining[..stop].trim_end().len().max(1)
}

const GENERATED_FILE_MARKERS: &[&str] = &[
    "automatically generated by rust-bindgen",
    "@generated",
    "DO NOT EDIT",
];

fn is_generated_file(path: &PathBuf) -> bool {
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut buf = [0u8; 1024];
    let n = f.read(&mut buf).unwrap_or(0);
    let head = std::str::from_utf8(&buf[..n]).unwrap_or("");
    GENERATED_FILE_MARKERS.iter().any(|m| head.contains(m))
}

pub async fn run_file_lints(rs_file_path: PathBuf, verbose: bool) -> io::Result<()> {
    if is_generated_file(&rs_file_path) {
        if verbose {
            println!(
                "[*] Skipping auto-generated file {}",
                rs_file_path.as_path().display()
            );
        }
        return Ok(());
    }

    let mut errors: Vec<String> = Vec::new();

    if let Err(e) = statement_order::run_item_order_check(rs_file_path.clone(), verbose).await {
        errors.push(e.to_string());
    }
    if let Err(e) =
        statement_order::run_mod_use_adjacency_check(rs_file_path.clone(), verbose).await
    {
        errors.push(e.to_string());
    }
    if let Err(e) = generics_order::run_generics_order_check(rs_file_path, verbose).await {
        errors.push(e.to_string());
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(io::Error::other(errors.join("\n\n")))
    }
}
