[package]
name = "libaflmm"
authors = [
  "Romain Malmain <rmalmain@pm.me>",
  "tokatoka <tokazerkje@outlook.com>",
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
description = "Slot your own fuzzers together and extend their features using Rust"
keywords = ["fuzzing", "testing", "security"]
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
features = ["document-features"]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[features]
default = [
  "derive",
  "errors_backtrace",
  "nautilus",
  "libaflmm_bolts/xxh3",
  "rand_trait",
  "simd",
  "serial_test",
]
document-features = ["dep:document-features"]

#! # Feature Flags
#! ### General Features

## Stores the backtraces of all generated `Error`s. Good for debugging, but may come with a slight performance hit.
errors_backtrace = ["libaflmm_bolts/errors_backtrace"]

## Switches from `HashMap` to `BTreeMap` for `CorpusId`
corpus_btreemap = []

## If this feature is set, `LibAFL` targets (and the fuzzer) will crash on `SIGPIPE` on unix systems.
handle_sigpipe = []

#! ## Additional Components

## Enables `WebMonitor`, an axum-based HTTP server exposing fuzzing stats and historical data
web_monitor = ["dep:axum", "dep:tokio"]

#! ## LibAFL-Bolts Features

## Provide the `#[derive(SerdeAny)]` macro.
derive = [
  "libaflmm_derive",
] # provide `derive(SerdeAny) macro.

## If set, libaflmm_bolt's `rand` implementations will implement `rand::Rng`
rand_trait = ["libaflmm_bolts/rand_trait"]

#! ### SerdeAny features

## Grammar mutator.
nautilus = ["rand_trait", "dep:regex-syntax", "dep:regex"]

## Python grammar support for nautilus
nautilus_py = ["nautilus", "dep:pyo3"]

## Use the best SIMD implementation by our benchmark
simd = ["libaflmm_bolts/simd"]

[build-dependencies]
rustversion = { workspace = true }

[dev-dependencies]
# clippy-suggested optimised byte counter
bytecount = "0.6.9"
rusty-fork = "0.3.1"

[dependencies]
libaflmm_bolts = { workspace = true }
libaflmm_core = { workspace = true }
libaflmm_derive = { workspace = true, default-features = true, optional = true }
libaflmm_targets = { workspace = true, default-features = true }

quanta = "0.12.6"
hashbrown = { workspace = true, features = [
  "serde",
  "default-hasher",
  "raw-entry",
], default-features = false } # A faster hashmap, nostd compatible
libm = "0.2.16"
log = { workspace = true }
meminterval = { workspace = true, features = ["serde"] }
nix = { workspace = true, features = [
  "signal",
  "poll",
  "ptrace",
  "personality",
  "fs",
  "mman",
] }
num-traits = { workspace = true, default-features = false }
postcard = { workspace = true } # no_std compatible serde serialization format
pyo3 = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true, default-features = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
humantime = "2.3"
tuple_list = { workspace = true }
typed-builder = { workspace = true } # Implement the builder pattern at compiletime

regex = { workspace = true, optional = true }
regex-syntax = { version = "0.8.10", optional = true } # For nautilus

axum = { version = "0.8", optional = true }
tokio = { version = "1.40.0", optional = true, features = [
  "sync",
  "net",
  "rt",
  "io-util",
  "macros",
  "rt-multi-thread",
  "time",
] } # used for `WebMonitor`

# optional-dev deps (change when target.'cfg(accessible(::std))'.test-dependencies will be stable)
serial_test = { workspace = true, optional = true, default-features = false, features = [
  "logging",
] }

# Document all features of this crate (for `cargo doc`)
document-features = { workspace = true, optional = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true } # For (*nix) libc

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Kernel",
  "Win32_System_Memory",
  "Win32_Security",
  "Win32_System_SystemInformation",
] }
winapi = { version = "0.3", features = [
  "dbghelp",
  "minwindef",
  "winnt",
  "errhandlingapi",
  "processthreadsapi",
] }
[target.'cfg(windows)'.build-dependencies]
windows = { workspace = true }
