[package]
name = "pylibafl"
description = "Python bindings for LibAFL"
keywords = ["fuzzing", "testing", "security", "python"]
categories = ["development-tools::testing", "emulators", "embedded", "os"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module"] }
pyo3-log = { version = "0.13.1" }
libaflmm_bolts = { workspace = true, features = ["python"] }

[target.'cfg(target_os = "linux")'.dependencies]
libaflmm_qemu = { workspace = true, features = ["python"] }

[build-dependencies]
pyo3-build-config = "0.28.3"

[lib]
name = "pylibafl"
crate-type = ["cdylib"]

# TODO: find a way to fix this when a solution is found
# https://github.com/rust-lang/cargo/issues/9330
# [profile.dev]
# panic = "abort"
