[package]
name = "find_llvm_config"
description = "A standalone binary to find the llvm-config path"
readme = "README.md"
keywords = ["fuzzing", "testing", "llvm"]
categories = ["development-tools::testing"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
libaflmm_build = { path = "../../crates/libaflmm_build" }
