[package]
name = "libaflmm_bolts"
authors = [
  "Romain Malmain <rmalmain@pm.me>",
  "tokatoka <tokazerkje@outlook.com>",
  "Andrea Fioraldi <andreafioraldi@gmail.com>",
  "Dominik Maier <domenukk@gmail.com>",
]
description = "Low-level bolts to create fuzzers and so much more"
keywords = ["fuzzing", "testing", "security"]
categories = ["development-tools::testing", "emulators", "embedded", "os"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
features = ["document-features"]
all-features = true

[features]
default = ["rand_trait", "xxh3", "simd"]
document-features = ["dep:document-features"]

#! # Feature Flags
#! ### General Features

## If set, libaflmm_bolt's `rand` implementations will implement `rand_core::TryRng`
## and, inversely, all seedable `rand_core::Rng` types can be used as Rng for LibAFL.
rand_trait = []

## Will build the `pyo3` bindings
python = ["pyo3", "libaflmm_core/python"]

## Stores the backtraces of all generated `Error`s. Good for debugging, but may come with a slight performance hit.
errors_backtrace = ["libaflmm_core/errors_backtrace"]

## Replaces `ahash` with the potentially faster [`xxh3`](https://github.com/Cyan4973/xxHash) in some parts of the lib.
## This yields a stable and fast hash, but may increase the resulting binary size slightly
## This also enables certain hashing and rand features in `no_std` no-alloc.
xxh3 = ["xxhash-rust"]

#! ### SerdeAny features

## With this feature, the AnyMap uses [`type_name`](https://doc.rust-lang.org/std/any/fn.type_name.html)
## instead of [`TypeId::of`](https://doc.rust-lang.org/std/any/struct.TypeId.html#method.of) for deserialization.
## With this feature, stored state remains deserializable across multiple compilations of LibAFL.
## The rust doc specifically states that "multiple types may map to the same type name", so it could potentially lead to bugs.
## However, we make sure that no two types with the same name ever exist.
stable_anymap = []

#! ### Stable SIMD features

## Use the best SIMD implementation by our benchmark.
simd = ["wide"]

[build-dependencies]
rustversion = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive", "env"] }
rand = "0.10.1"
chrono = "0.4.44"
itertools = "0.14.0"

[dependencies]
rangemap = { workspace = true }
libaflmm_core = { workspace = true, features = ["serde"] }

num_enum = { workspace = true }
rand_core = { workspace = true }
uuid = { workspace = true }
ahash = { workspace = true } # The hash function already used in hashbrown
clap = { workspace = true, features = [
  "derive",
  "wrap_help",
], optional = true } # CLI parsing, for libaflmm_bolts::cli / the `cli` feature
xxhash-rust = { version = "0.8.15", features = [
  "xxh3",
], optional = true } # xxh3 hashing for rust
serde = { workspace = true, default-features = false, features = [
  "derive",
] } # serialization lib

log = { workspace = true }
nix = { workspace = true, default-features = false, features = [
  "fs",
  "signal",
  "socket",
  "poll",
  "time",
  "mman",
] }
pyo3 = { workspace = true, optional = true, features = ["serde", "macros"] }
bytemuck = "1.25.0"

# optional stable simd
wide = { version = "1.4.0", optional = true }
atomic = "0.6.1"
num-traits = { workspace = true }
ctor = { workspace = true }
erased-serde = { workspace = true, default-features = true }
hashbrown = { workspace = true, features = [
  "serde",
  "default-hasher",
  "raw-entry",
] }
postcard = { workspace = true }
static_assertions = { workspace = true }
tuple_list = { workspace = true }
typeid = { workspace = true }

# Document all features of this crate (for `cargo doc`)
document-features = { workspace = true, optional = true }

[lints]
workspace = true

[target.'cfg(unix)'.dependencies]
libc = { workspace = true } # For (*nix) libc

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Console",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Kernel",
  "Win32_System_Memory",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
] }
winapi = { version = "0.3", features = [
  "fileapi",
  "handleapi",
  "processenv",
  "processthreadsapi",
  "winbase",
  "winnt",
] }
windows-result = "0.4.1"

[target.'cfg(windows)'.build-dependencies]
windows = { workspace = true }

[target.'cfg(target_vendor = "apple")'.dependencies]
mach2 = "0.6.0"

#[profile.release]
#lto = true
#opt-level = 3
#debug = true


[[example]]
name = "simd"
path = "./examples/simd/simd.rs"
bench = true
test = false
harness = false
required-features = ["simd"]
