import "../../../just/libafl.just"
FUZZER_NAME := "sqlite3"

build:
    ./build.sh {{ PROFILE }}

test: build
    #!/bin/bash
    set -eu

    timeout 20s ./ossfuzz

    STATS_FILE="./workdir/worker_0/fuzzer_stats"
    if [ ! -f "$STATS_FILE" ]; then
        echo "sqlite: Stats file not found at $STATS_FILE"
        exit 1
    fi

    OBJECTIVE=$(jq '.' "$STATS_FILE")
    if [ "$OBJECTIVE" -eq 0 ]; then
        echo "sqlite: Fuzzer did not find any objective (stats: $STATS_FILE)"
        exit 1
    else
        echo "sqlite: Found $OBJECTIVE objective(s)."
    fi
