import "../../../just/libafl.just"
FUZZER_NAME := "sqlite3"

build:
    ./build.sh --locked {{ PROFILE }}

run: build
    ./ossfuzz --input corpus

test: build
    #!/bin/bash
    set -eu

    timeout 40s ./ossfuzz --input corpus || true

    STATS_FILE="./workdir/worker_0/fuzzer_stats"
    if [ ! -f "$STATS_FILE" ]; then
        echo "sqlite: Stats file not found at $STATS_FILE"
        exit 1
    fi

    CORPUS=$(jq '.corpus' "$STATS_FILE")
    if [ "$CORPUS" -lt 100 ]; then
        echo "sqlite: Fuzzer did not find more than 100 new interesting inputs (stats: $STATS_FILE, corpus found: $CORPUS)"
        exit 1
    else
        echo "sqlite: Found $CORPUS new interesting input(s). success."
    fi
