[package]
name = "build_and_test_fuzzers"
description = "Get diffing fuzzers from the last commit"
keywords = ["ci"]
categories = ["development-tools::testing"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
cargo_toml = "0.22.3"
walkdir = "2.5.0"

[lints]
workspace = true
