[package]
name = "pylibaflmm"
description = "Python bindings for LibAFL--"
keywords = ["fuzzing", "testing", "security", "python"]
categories = ["development-tools::testing", "emulators", "embedded", "os"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
libaflmm_bolts = { workspace = true, features = ["python"] }

pyo3 = { workspace = true }
pyo3-log = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libaflmm_qemu = { workspace = true, features = ["python"] }

[build-dependencies]
pyo3-build-config = { workspace = true }

[lib]
name = "pylibaflmm"
crate-type = ["cdylib"]

# TODO: find a way to fix this when a solution is found
# https://github.com/rust-lang/cargo/issues/9330
# [profile.dev]
# panic = "abort"
