[package]
name = "libaflmm_intelpt"
authors = ["Marco Cavenati <cavenatimarco@gmail.com>"]
description = "Intel Processor Trace wrapper for libafl"
keywords = ["fuzzing", "testing", "security", "intelpt"]
categories = ["development-tools::testing", "no-std"]

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
## Export raw Intel PT traces on decode, useful for debug, disabled by default for best performance
export_raw = []
## Expose LibAFL QEMU module
qemu = ["dep:libaflmm_qemu"]

[dev-dependencies]
static_assertions = { workspace = true }

[target.'cfg(target_os = "linux" )'.dev-dependencies]
nix = { workspace = true }
proc-maps = "0.4.0"

[dependencies]
libaflmm = { workspace = true, default-features = false }
libaflmm_qemu = { workspace = true, default-features = false, features = [
  "systemmode",
], optional = true }

arbitrary-int = { workspace = true }
bitbybit = { workspace = true }
libaflmm_bolts = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true, default-features = false }
num-traits = { workspace = true, default-features = false }
ptcov = { version = "0.0.6" }
raw-cpuid = { version = "11.6.0" }
serde = { workspace = true }
typed-builder = { workspace = true }

[target.'cfg(target_os = "linux" )'.dependencies]
caps = { version = "0.5.6" }
perf-event-open-sys = { version = "6.0.0" }

[lints]
workspace = true
