[package]
name = "libaflmm_repo_tools"
description = "A set of useful tools to manage the LibAFL repository"
authors = ["Romain Malmain <romain.malmain@pm.me>"]
keywords = ["libafl", "tools"]
categories = ["development-tools"]
readme = "README.md"

documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
project-root = "0.2"
walkdir = "2.5"
regex = "1.10"
tokio = { version = "1.44", features = [
  "process",
  "rt",
  "rt-multi-thread",
  "macros",
] }
clap = { version = "4.5", features = ["derive"] }
exitcode = "1.1"
which = "7.0.2"
colored = "3.0.0"
syn = { version = "2", features = ["parsing", "full"] }
proc-macro2 = { version = "1", features = ["span-locations"] }

[lints]
workspace = true
