[book]
authors = ["Romain Malmain", "tokatoka <tokazerkje@outlook.com>"]
language = "en"
src = "src"
title = "The LibAFL-- Fuzzing Library"

[preprocessor.vale]
command = "./vale-check.py"

[preprocessor.drawio]
command = "mdbook-drawio"

[preprocessor.lychee]
command = "./lychee-check.py"

[output.html]

# [output.linkcheck]
# optional = true
