name: build and test
permissions:
  contents: read

on:
  push:
    branches: [main, "pr/**"]
  pull_request:
    branches: [main]
    types: ["labeled", "opened", "synchronize", "reopened"]
  workflow_dispatch:
  merge_group:
env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  MAIN_LLVM_VERSION: 22

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt-base
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - run: cargo build
