name: build and test
permissions:
  contents: read

on:
  push:
    branches: [main, "pr/**"]
  pull_request:
    branches: [main]
    types: ["labeled", "opened", "synchronize", "reopened"]
  workflow_dispatch:
  merge_group:
  schedule:
    - cron: "0 6 * * 1" # Re-run every mondays at 06:00 UTC in case a new lint break everything
env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  MAIN_LLVM_VERSION: 22

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Check for blobs
        run: ./scripts/check_for_blobs.sh
      - name: Check for conflicting dependency versions
        run: cargo tree -d --workspace
      - name: Build workspace (Debug)
        run: cargo build --workspace --all-targets --exclude libaflmm_asan_libc --exclude libaflmm_frida --exclude args_reorder --exclude generics_reorder --exclude use_after_mod
      - name: Test examples
        run: cargo test --workspace --all-targets --exclude libaflmm_asan --exclude libaflmm_asan_fuzz --exclude libaflmm_asan_libc --exclude libaflmm_frida --exclude args_reorder --exclude generics_reorder --exclude use_after_mod --examples
      - name: Build docs
        run: ./scripts/doc_all.py
      - name: Run tests serially
        run: cargo test -- --test-threads 1
      - name: Check sancov pcguard edges
        run: cargo check --features=sancov_pcguard_edges
      - name: Shellcheck
        run: shellcheck ./scripts/*.sh

  ubuntu-miri:
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    if: contains( github.event.pull_request.labels.*.name, 'pre-release')
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          components: miri
          cache-key: ubuntu-miri
      - name: Run miri tests
        run: RUST_BACKTRACE=1 MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test

  ubuntu-clippy:
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Run clippy
        run: ./scripts/clippy.sh

  ubuntu-check:
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      matrix:
        instance_idx:
          [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
          ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          components: clippy, rustfmt
          cache-key: ubuntu
      - name: Check each feature
        env:
          CI_INSTANCES: 18
          LLVM_VERSION: ${{ env.MAIN_LLVM_VERSION }}
        run: cargo run --manifest-path utils/ci_splitter/Cargo.toml -- ${{ matrix.instance_idx }}

  cargo-fmt:
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Installing python3 black
        run: command -v black &>/dev/null || pipx install black
      - name: Check formatting
        run: ./scripts/fmt_all.sh check

  check-md-links:
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          fail_on_error: "true"
          config_file: ".github/.linkspector.yml"

  fuzzers:
    name: Testing ${{ matrix.fuzzer }}
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/baby_cmplog
          - baby/baby_forkserver
          - baby/baby_inprocess
    env:
      PROFILE: dev # build in debug mode to speed up the tests
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Configure Cache
        uses: Swatinem/rust-cache@v2
        with:
          # We will have these guys all share a cache (since they should share
          # and awful lot of their dependencies). That way we won't use up
          # as much space.
          shared-key: fuzzers-x86_64
          # We want to include the commit hash to ensure the cache is replaced
          # on each new commit.
          key: ${{ github.sha }}
          # We will only save the cache for one of the builds. Though we could
          # just omit this filter and the jobs race to push to the cache, since
          # they would all share the same key (combining the `shared-key` and
          # `key`) our build would generate a load of warnings. Why this
          # particular fuzzer? No real reason, but we had to choose one.
          save-if: ${{ matrix.fuzzer == 'binary_only/frida_libpng' }}
          cache-all-crates: true
          # The code is built in the fuzzers own directory, not in the target
          # directory in the root of the workspace
          workspaces: |
            fuzzers/${{ matrix.fuzzer }}
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test

  fuzzers-qemu:
    name: Testing ${{ matrix.fuzzer }} (QEMU)
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/baby_nyx
    env:
      PROFILE: dev # build in debug mode to speed up the tests
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ env.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Configure Cache
        uses: Swatinem/rust-cache@v2
        with:
          # We will have these guys all share a cache (since they should share
          # and awful lot of their dependencies). That way we won't use up
          # as much space.
          shared-key: fuzzers-x86_64
          # We want to include the commit hash to ensure the cache is replaced
          # on each new commit.
          key: ${{ github.sha }}
          # We will only save the cache for one of the builds. Though we could
          # just omit this filter and the jobs race to push to the cache, since
          # they would all share the same key (combining the `shared-key` and
          # `key`) our build would generate a load of warnings. Why this
          # particular fuzzer? No real reason, but we had to choose one.
          save-if: ${{ matrix.fuzzer == 'binary_only/frida_libpng' }}
          cache-all-crates: true
          # The code is built in the fuzzers own directory, not in the target
          # directory in the root of the workspace
          workspaces: |
            fuzzers/${{ matrix.fuzzer }}
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test
