name: "CI - Build"
on:
  workflow_call: {}

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      CROSS_CC: gcc
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - uses: ./.github/actions/cache-qemu-nyx
      - name: check for conflicting dependency versions
        run: cargo tree --locked -d --workspace
      - name: build workspace (debug)
        run: cargo build --locked --workspace --all-targets --exclude libaflmm_asan_libc --exclude args_reorder --exclude generics_reorder --exclude use_after_mod
      - name: test examples
        run: cargo test --locked --workspace --all-targets --exclude libaflmm_asan --exclude libaflmm_asan_fuzz --exclude libaflmm_asan_libc --exclude args_reorder --exclude generics_reorder --exclude use_after_mod --examples
      - name: build docs
        run: ./scripts/doc_all.py
      - name: run tests serially
        run: cargo test --locked -- --test-threads 1
      - name: check sancov pcguard edges
        run: cargo check --locked --features=sancov_pcguard_edges
      - name: shellcheck
        run: shellcheck ./scripts/*.sh

  ubuntu-qemu:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'qemu-full') || contains( github.event.pull_request.labels.*.name, 'pre-release')
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - i386
          - arm
          - aarch64
          - mips
          - ppc
          - hexagon
          - riscv32
          - riscv64
        mode:
          - usermode
          - systemmode
        exclude:
          - arch: hexagon
            mode: systemmode
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Build LibAFLmm QEMU ${{ matrix.mode }} - ${{ matrix.arch }}
        run: cargo build --locked -p libaflmm_qemu --no-default-features --features ${{ matrix.mode }},${{ matrix.arch }}

  ubuntu-qemu-nyx:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'qemu-full') || contains( github.event.pull_request.labels.*.name, 'pre-release')
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Build LibAFLmm QEMU with Nyx API (systemmode - x86_64)
        run: cargo build --locked -p libaflmm_qemu --no-default-features --features systemmode,x86_64,nyx
