name: "CI - Fuzzers"
on:
  workflow_call: {}

jobs:
  fuzzers:
    name: Testing ${{ matrix.fuzzer }}
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/baby_cmplog
          - baby/baby_forkserver
          - baby/baby_inprocess

          # In process
          - inprocess/sqlite
    env:
      PROFILE: dev # build in debug mode to speed up the tests
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
          cache: ${{ vars.RUNS_ON != '' }}
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test

  fuzzers-qemu:
    name: Testing ${{ matrix.fuzzer }} (QEMU)
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/baby_nyx

          # Full-system
          - full_system/qemu_baremetal
    env:
      PROFILE: dev # build in debug mode to speed up the tests
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
          cache: ${{ vars.RUNS_ON != '' }}
      - uses: ./.github/actions/cache-qemu-nyx
        with:
          target-dir: fuzzers/${{ matrix.fuzzer }}/target/debug
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test
