name: "CI - Fuzzers"
on:
  workflow_call: {}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      standard: ${{ steps.fuzzers.outputs.standard }}
      qemu: ${{ steps.fuzzers.outputs.qemu }}
    steps:
      - uses: actions/checkout@v6
      - name: Read fuzzer list
        id: fuzzers
        run: >-
          cargo run --quiet --locked
          --manifest-path utils/libaflmm_repo_tools/Cargo.toml
          -- --fuzzer-matrix >> "$GITHUB_OUTPUT"

  fuzzers:
    needs: matrix
    name: Testing ${{ matrix.fuzzer }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fuzzer: ${{ fromJSON(needs.matrix.outputs.standard) }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          aflplusplus: true # useful for forkserver
      - uses: ./.github/actions/setup-llvm
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test

  fuzzers-qemu:
    needs: matrix
    name: Testing ${{ matrix.fuzzer }} (QEMU)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fuzzer: ${{ fromJSON(needs.matrix.outputs.qemu) }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - uses: ./.github/actions/cache-qemu-nyx
        with:
          target-dir: fuzzers/${{ matrix.fuzzer }}/target/debug
      - uses: ./.github/actions/cache-qemu
        with:
          target-dir: fuzzers/${{ matrix.fuzzer }}/target/release
          build-id: ${{ matrix.fuzzer }}
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test
