name: "CI - Fuzzers"
on:
  workflow_call: {}

jobs:
  fuzzers:
    name: Testing ${{ matrix.fuzzer }}
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/baby_cmplog
          - baby/baby_forkserver
          - baby/baby_inprocess

          # In process
          - inprocess/sqlite
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          aflplusplus: true # useful for forkserver
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
          cache: ${{ vars.RUNS_ON != '' }}
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test

  # anything fuzzers using nightly tool chain
  nightly-fuzzers:
    name: Testing ${{ matrix.fuzzer }} (nightly)
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/tutorial
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          aflplusplus: true # useful for forkserver
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          cache-key: ubuntu-nightly
          cache: ${{ vars.RUNS_ON != '' }}
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test

  fuzzers-qemu:
    name: Testing ${{ matrix.fuzzer }} (QEMU)
    runs-on: ${{ fromJSON(vars.RUNS_ON || '["self-hosted","linux"]') }}
    strategy:
      fail-fast: false
      matrix:
        fuzzer:
          # Tutorial
          - baby/baby_nyx

          # Full-system
          - full_system/qemu_baremetal
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
          cache: ${{ vars.RUNS_ON != '' }}
      - uses: ./.github/actions/cache-qemu-nyx
        with:
          target-dir: fuzzers/${{ matrix.fuzzer }}/target/debug
      - name: Run test
        shell: bash
        run: |
          cd fuzzers/${{ matrix.fuzzer }}
          just test
