name: "CI - Lints"
on:
  workflow_call: {}

jobs:
  ubuntu-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - uses: ./.github/actions/cache-qemu-nyx
      - name: Check repository
        run: ./scripts/check.sh

  ubuntu-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # check CI_INSTANCES if you change that to match
        instance_idx: ["0", "1"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
        with:
          qemu: true
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          components: clippy, rustfmt
          cache-key: ubuntu
      - uses: ./.github/actions/cache-qemu-nyx
      - name: Check each feature
        env:
          # check instance_idx if you change that to match
          CI_INSTANCES: 4
          LLVM_VERSION: ${{ vars.MAIN_LLVM_VERSION }}
        run: cargo run --locked --manifest-path utils/ci_splitter/Cargo.toml -- ${{ matrix.instance_idx }}

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - uses: ./.github/actions/setup-llvm
        with:
          version: ${{ vars.MAIN_LLVM_VERSION }}
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: ubuntu
      - name: Installing python3 black
        run: command -v black &>/dev/null || pipx install black
      - name: Check formatting
        run: ./scripts/fmt.sh check

  check-md-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          fail_on_error: "true"
          config_file: ".github/.linkspector.yml"
