name: "CI - miri"
on:
  workflow_call: {}

jobs:
  ubuntu-miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/apt
      - uses: ./.github/actions/setup-llvm
      - uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: miri
          cache-key: ubuntu-miri
      - name: Run miri tests
        run: RUST_BACKTRACE=1 MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test --locked
