name: "Dependabot - Cargo lockfiles"

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  update:
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      startsWith(github.event.pull_request.head.ref, 'dependabot/cargo/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Generate Cargo lockfiles
        run: ./scripts/gen_lockfiles.sh

      - name: Commit Cargo lockfiles
        run: |
          git add -- Cargo.lock ':(glob)**/Cargo.lock'
          git diff --cached --quiet && exit 0
          git config user.name "github-actions[bot]"
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Cargo lockfiles"

      - name: Push Cargo lockfiles
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          git push \
            "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" \
            "HEAD:refs/heads/$HEAD_REF"
